# Put application-specific config here (application name: client-config-app)
some:
  property=app specific overridden value
new:
  property=Hello world



spring:
  application:
    name: config-client-app
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    enabled: true
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
